# Generated by Django 3.1.4 on 2021-02-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IW_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
