# Generated by Django 3.1.4 on 2021-02-11 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IW_App', '0002_teammember_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='slug',
        ),
    ]
