# Generated by Django 3.1.4 on 2021-02-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IW_App', '0003_remove_teammember_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessadvise',
            options={'ordering': ('ba_title',)},
        ),
        migrations.AddField(
            model_name='businessadvise',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AlterIndexTogether(
            name='businessadvise',
            index_together={('id', 'slug')},
        ),
    ]
