# Generated by Django 3.1.4 on 2021-02-14 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IW_App', '0004_auto_20210214_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClintFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='AboutUS',
        ),
        migrations.DeleteModel(
            name='Policy',
        ),
        migrations.RemoveField(
            model_name='clienteducation',
            name='file',
        ),
        migrations.AddField(
            model_name='clintfile',
            name='clint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IW_App.clienteducation'),
        ),
    ]
